import type { Metadata } from 'next';
import './globals.css';
import { ChakraProvider } from '@chakra-ui/react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ChakraProvider>{children}</ChakraProvider>
      </body>
    </html>
  );
}
